#pragma once

namespace ZG
{
    enum class KeyAction
    {
        PRESS, REPEAT, RELEASE
    };

    /**
     * Mapped to 7-bit ASCII. Mirrors GLFW defines.  
     */

    #define ZG_KEY_UNKNOWN       -1
    #define ZG_KEY_SPACE         32
    #define ZG_KEY_APOSTROPHE    39
    #define ZG_KEY_COMMA         44
    #define ZG_KEY_MINUS         45
    #define ZG_KEY_PERIOD        46
    #define ZG_KEY_SLASH         47
    #define ZG_KEY_0             48
    #define ZG_KEY_1             49
    #define ZG_KEY_2             50
    #define ZG_KEY_3             51
    #define ZG_KEY_4             52
    #define ZG_KEY_5             53
    #define ZG_KEY_6             54
    #define ZG_KEY_7             55
    #define ZG_KEY_8             56
    #define ZG_KEY_9             57
    #define ZG_KEY_SEMICOLON     59
    #define ZG_KEY_EQUAL         61
    #define ZG_KEY_A             65
    #define ZG_KEY_B             66
    #define ZG_KEY_C             67
    #define ZG_KEY_D             68
    #define ZG_KEY_E             69
    #define ZG_KEY_F             70
    #define ZG_KEY_G             71
    #define ZG_KEY_H             72
    #define ZG_KEY_I             73
    #define ZG_KEY_J             74
    #define ZG_KEY_K             75
    #define ZG_KEY_L             76
    #define ZG_KEY_M             77
    #define ZG_KEY_N             78
    #define ZG_KEY_O             79
    #define ZG_KEY_P             80
    #define ZG_KEY_Q             81
    #define ZG_KEY_R             82
    #define ZG_KEY_S             83
    #define ZG_KEY_T             84
    #define ZG_KEY_U             85
    #define ZG_KEY_V             86
    #define ZG_KEY_W             87
    #define ZG_KEY_X             88
    #define ZG_KEY_Y             89
    #define ZG_KEY_Z             90
    #define ZG_KEY_LEFT_BRACKET  91
    #define ZG_KEY_BACKSLASH     92
    #define ZG_KEY_RIGHT_BRACKET 93
    #define ZG_KEY_GRAVE_ACCENT  96
    #define ZG_KEY_WORLD_1       161
    #define ZG_KEY_WORLD_2       162
    #define ZG_KEY_ESCAPE        256
    #define ZG_KEY_ENTER         257
    #define ZG_KEY_TAB           258
    #define ZG_KEY_BACKSPACE     259
    #define ZG_KEY_INSERT        260
    #define ZG_KEY_DELETE        261
    #define ZG_KEY_RIGHT         262
    #define ZG_KEY_LEFT          263
    #define ZG_KEY_DOWN          264
    #define ZG_KEY_UP            265
    #define ZG_KEY_PAGE_UP       266
    #define ZG_KEY_PAGE_DOWN     267
    #define ZG_KEY_HOME          268
    #define ZG_KEY_END           269
    #define ZG_KEY_CAPS_LOCK     280
    #define ZG_KEY_SCROLL_LOCK   281
    #define ZG_KEY_NUM_LOCK      282
    #define ZG_KEY_PRINT_SCREEN  283
    #define ZG_KEY_PAUSE         284
    #define ZG_KEY_F1            290
    #define ZG_KEY_F2            291
    #define ZG_KEY_F3            292
    #define ZG_KEY_F4            293
    #define ZG_KEY_F5            294
    #define ZG_KEY_F6            295
    #define ZG_KEY_F7            296
    #define ZG_KEY_F8            297
    #define ZG_KEY_F9            298
    #define ZG_KEY_F10           299
    #define ZG_KEY_F11           300
    #define ZG_KEY_F12           301
    #define ZG_KEY_F13           302
    #define ZG_KEY_F14           303
    #define ZG_KEY_F15           304
    #define ZG_KEY_F16           305
    #define ZG_KEY_F17           306
    #define ZG_KEY_F18           307
    #define ZG_KEY_F19           308
    #define ZG_KEY_F20           309
    #define ZG_KEY_F21           310
    #define ZG_KEY_F22           311
    #define ZG_KEY_F23           312
    #define ZG_KEY_F24           313
    #define ZG_KEY_F25           314
    #define ZG_KEY_KP_0          320
    #define ZG_KEY_KP_1          321
    #define ZG_KEY_KP_2          322
    #define ZG_KEY_KP_3          323
    #define ZG_KEY_KP_4          324
    #define ZG_KEY_KP_5          325
    #define ZG_KEY_KP_6          326
    #define ZG_KEY_KP_7          327
    #define ZG_KEY_KP_8          328
    #define ZG_KEY_KP_9          329
    #define ZG_KEY_KP_DECIMAL    330
    #define ZG_KEY_KP_DIVIDE     331
    #define ZG_KEY_KP_MULTIPLY   332
    #define ZG_KEY_KP_SUBTRACT   333
    #define ZG_KEY_KP_ADD        334
    #define ZG_KEY_KP_ENTER      335
    #define ZG_KEY_KP_EQUAL      336
    #define ZG_KEY_LEFT_SHIFT    340
    #define ZG_KEY_LEFT_CONTROL  341
    #define ZG_KEY_LEFT_ALT      342
    #define ZG_KEY_LEFT_SUPER    343
    #define ZG_KEY_RIGHT_SHIFT   344
    #define ZG_KEY_RIGHT_CONTROL 345
    #define ZG_KEY_RIGHT_ALT     346
    #define ZG_KEY_RIGHT_SUPER   347
    #define ZG_KEY_MENU          348
    #define ZG_KEY_LAST          ZG_KEY_MENU

    enum class KeyCode : int
    {
        UNKNOWN       = ZG_KEY_UNKNOWN,
        SPACE         = ZG_KEY_SPACE,
        APOSTROPHE    = ZG_KEY_APOSTROPHE,
        COMMA         = ZG_KEY_COMMA,
        MINUS         = ZG_KEY_MINUS,
        PERIOD        = ZG_KEY_PERIOD,
        SLASH         = ZG_KEY_SLASH,
        ZERO          = ZG_KEY_0,
        ONE           = ZG_KEY_1,
        TWO           = ZG_KEY_2,
        THREE         = ZG_KEY_3,
        FOUR          = ZG_KEY_4,
        FIVE          = ZG_KEY_5,
        SIX           = ZG_KEY_6,
        SEVEN         = ZG_KEY_7,
        EIGHT         = ZG_KEY_8,
        NINE          = ZG_KEY_9,
        SEMICOLON     = ZG_KEY_SEMICOLON,
        EQUAL         = ZG_KEY_EQUAL,
        A             = ZG_KEY_A,
        B             = ZG_KEY_B,
        C             = ZG_KEY_C,
        D             = ZG_KEY_D,
        E             = ZG_KEY_E,
        F             = ZG_KEY_F,
        G             = ZG_KEY_G,
        H             = ZG_KEY_H,
        I             = ZG_KEY_I,
        J             = ZG_KEY_J,
        K             = ZG_KEY_K,
        L             = ZG_KEY_L,
        M             = ZG_KEY_M,
        N             = ZG_KEY_N,
        O             = ZG_KEY_O,
        P             = ZG_KEY_P,
        Q             = ZG_KEY_Q,
        R             = ZG_KEY_R,
        S             = ZG_KEY_S,
        T             = ZG_KEY_T,
        U             = ZG_KEY_U,
        V             = ZG_KEY_V,
        W             = ZG_KEY_W,
        X             = ZG_KEY_X,
        Y             = ZG_KEY_Y,
        Z             = ZG_KEY_Z,
        LEFT_BRACKET  = ZG_KEY_LEFT_BRACKET,
        BACKSLASH     = ZG_KEY_BACKSLASH,
        RIGHT_BRACKET = ZG_KEY_RIGHT_BRACKET,
        GRAVE_ACCENT  = ZG_KEY_GRAVE_ACCENT,
        WORLD_1       = ZG_KEY_WORLD_1,
        WORLD_2       = ZG_KEY_WORLD_2,
        ESCAPE        = ZG_KEY_ESCAPE,
        ENTER         = ZG_KEY_ENTER,
        TAB           = ZG_KEY_TAB,
        BACKSPACE     = ZG_KEY_BACKSPACE,
        INSERT        = ZG_KEY_INSERT,
        DELETE        = ZG_KEY_DELETE,
        RIGHT         = ZG_KEY_RIGHT,
        LEFT          = ZG_KEY_LEFT,
        DOWN          = ZG_KEY_DOWN,
        UP            = ZG_KEY_UP,
        PAGE_UP       = ZG_KEY_PAGE_UP,
        PAGE_DOWN     = ZG_KEY_PAGE_DOWN,
        HOME          = ZG_KEY_HOME,
        END           = ZG_KEY_END,
        CAPS_LOCK     = ZG_KEY_CAPS_LOCK,
        SCROLL_LOCK   = ZG_KEY_SCROLL_LOCK,
        NUM_LOCK      = ZG_KEY_NUM_LOCK,
        PRINT_SCREEN  = ZG_KEY_PRINT_SCREEN,
        PAUSE         = ZG_KEY_PAUSE,
        F1            = ZG_KEY_F1,
        F2            = ZG_KEY_F2,
        F3            = ZG_KEY_F3,
        F4            = ZG_KEY_F4,
        F5            = ZG_KEY_F5,
        F6            = ZG_KEY_F6,
        F7            = ZG_KEY_F7,
        F8            = ZG_KEY_F8,
        F9            = ZG_KEY_F9,
        F10           = ZG_KEY_F10,
        F11           = ZG_KEY_F11,
        F12           = ZG_KEY_F12,
        F13           = ZG_KEY_F13,
        F14           = ZG_KEY_F14,
        F15           = ZG_KEY_F15,
        F16           = ZG_KEY_F16,
        F17           = ZG_KEY_F17,
        F18           = ZG_KEY_F18,
        F19           = ZG_KEY_F19,
        F20           = ZG_KEY_F20,
        F21           = ZG_KEY_F21,
        F22           = ZG_KEY_F22,
        F23           = ZG_KEY_F23,
        F24           = ZG_KEY_F24,
        F25           = ZG_KEY_F25,
        KP_0          = ZG_KEY_KP_0,
        KP_1          = ZG_KEY_KP_1,
        KP_2          = ZG_KEY_KP_2,
        KP_3          = ZG_KEY_KP_3,
        KP_4          = ZG_KEY_KP_4,
        KP_5          = ZG_KEY_KP_5,
        KP_6          = ZG_KEY_KP_6,
        KP_7          = ZG_KEY_KP_7,
        KP_8          = ZG_KEY_KP_8,
        KP_9          = ZG_KEY_KP_9,
        KP_DECIMAL    = ZG_KEY_KP_DECIMAL,
        KP_DIVIDE     = ZG_KEY_KP_DIVIDE,
        KP_MULTIPLY   = ZG_KEY_KP_MULTIPLY,
        KP_SUBTRACT   = ZG_KEY_KP_SUBTRACT,
        KP_ADD        = ZG_KEY_KP_ADD,
        KP_ENTER      = ZG_KEY_KP_ENTER,
        KP_EQUAL      = ZG_KEY_KP_EQUAL,
        LEFT_SHIFT    = ZG_KEY_LEFT_SHIFT,
        LEFT_CONTROL  = ZG_KEY_LEFT_CONTROL,
        LEFT_ALT      = ZG_KEY_LEFT_ALT,
        LEFT_SUPER    = ZG_KEY_LEFT_SUPER,
        RIGHT_SHIFT   = ZG_KEY_RIGHT_SHIFT,
        RIGHT_CONTROL = ZG_KEY_RIGHT_CONTROL,
        RIGHT_ALT     = ZG_KEY_RIGHT_ALT,
        RIGHT_SUPER   = ZG_KEY_RIGHT_SUPER,
        MENU          = ZG_KEY_MENU,
        LAST          = ZG_KEY_LAST,
    };
};